name: GitHub Actions Demo
on: [push]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Exécutez votre commande Docker build à partir du répertoire tp2
      - name: Display path
        run:  pwd

        # Exécutez votre commande Docker build à partir du répertoire tp2
      - name: Display files
        run:  cd tp2 && ls

      # Exécutez votre commande Docker build à partir du répertoire tp2
      - name: Docker build
        # docker build -t test -f tp2/Dockerfile tp2/  
        run:  docker build -t test -f tp2/Dockerfile tp2/  
        
      - name: Push Docker image to Docker Hub
        run: docker push bblksam16/tp2:latest