name: GitHub Actions Demo
on:
  push:
    paths:
      - ./tp3/**
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and tag the image
        run: docker build -t bblksam16/tp2:v3 ./tp2

      - name: Push Docker image to Docker Hub
        run: docker push bblksam16/tp2:v3
