name: GitHub Actions Demo
on: [push]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Entrer dans le répertoire tp2
      - name: Change to tp2 directory
        run: cd tp2 && ls

      # Exécutez votre commande Docker build à partir du répertoire tp2
      - name: Docker build
        run: cd tp2 && docker build -t bblksam16/tp2:latest -f Dockerfile .
        
      - name: Push Docker image to Docker Hub
        run: docker push bblksam16/tp2:latest