name: GitHub Actions Demo
on:
  push:
    paths:
      - "tp3/**"
      - ".github/workflows/tp3.yaml"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log in to Azure Container Registry
        uses: Azure/login@v2.1.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Push to ACR
        run: |
          docker tag bblksam16/tp3:v1 acr-tp3.azurecr.io/bblksam16/tp3:v1
          docker push acr-tp3.azurecr.io/bblksam16/tp3:v1