name: GitHub Actions Demo
on:
  push:
    paths:
      - "tp3/**"
      - ".github/workflows/tp3.yaml"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and tag the image
        run: docker build -t bblksam16/tp3:v1 ./tp3

      - name: Push Docker image to Docker Hub
        run: docker push bblksam16/tp3:v1

      - name: Log in to Azure Container Registry
        env:
          REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          az login --service-principal -u $AZURE_CREDENTIALS -p $AZURE_CREDENTIALS_PASSWORD --tenant $AZURE_TENANT_ID
          az acr login --name $REGISTRY_LOGIN_SERVER --username $REGISTRY_USERNAME --password $REGISTRY_PASSWORD